${pojo.packageDeclaration}

import com.kaidin.appframe.service.dao.IBaseDao;
import com.kaidin.db.entity.${pojo.declarationName};

/**
${pojo.getClassJavaDoc("generated by Hibernate Tools ${version}", 0)}
${pojo.getClassJavaDoc("@date ${date}", 0)}
 */
public interface I${pojo.getDeclarationName()}Dao extends IBaseDao<${pojo.getDeclarationName()}> {
	String RESOURCE_NAME = "I${pojo.getDeclarationName()}Dao";
}
