${pojo.packageDeclaration}

import org.springframework.stereotype.Repository;

import com.kaidin.appframe.service.dao.impl.BaseDaoHibernateImpl;
import com.kaidin.db.dao.I${pojo.getDeclarationName()}Dao;
import com.kaidin.db.entity.${pojo.getDeclarationName()};

/**
${pojo.getClassJavaDoc("${pojo.declarationName}DaoImpl generated by Hibernate Tools ${version}", 0)}
${pojo.getClassJavaDoc("@date ${date}", 0)}
 */
@Repository(I${pojo.getDeclarationName()}Dao.RESOURCE_NAME)
public class ${pojo.declarationName}DaoImpl extends BaseDaoHibernateImpl<${pojo.declarationName}> implements I${pojo.declarationName}Dao {

	public ${pojo.declarationName}DaoImpl() throws Exception {
		super(${pojo.declarationName}.class);
	}
}
