/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by Hibernate Tools ${version}", 0)}
 * @date ${date}
 */
<#include "Ejb3TypeDeclaration.ftl"/>
<#if pojo.getExtendsDeclaration().equals("")>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} extends BaseEntity
<#else>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} ${pojo.getExtendsDeclaration()} 
</#if>
<#-- 
继承的抽象基类BaseEntity已经实现序列化接口
${pojo.getImplementsDeclaration()} -->