package com.kaidin.db.dao.impl;

import org.springframework.stereotype.Repository;

import com.kaidin.appframe.service.dao.impl.BaseDaoHibernateImpl;
import com.kaidin.db.dao.IEntityCfgMenuDao;
import com.kaidin.db.entity.EntityCfgMenu;

/**
 * EntityCfgMenuDaoImpl generated by Hibernate Tools 3.3.0.GA
 * @date 2020-9-1 17:02:04
 */
@Repository(IEntityCfgMenuDao.RESOURCE_NAME)
public class EntityCfgMenuDaoImpl extends BaseDaoHibernateImpl<EntityCfgMenu> implements IEntityCfgMenuDao {

	public EntityCfgMenuDaoImpl() throws Exception {
		super(EntityCfgMenu.class);
	}
}
