package com.kaidin.db.dao.impl;

import org.springframework.stereotype.Repository;

import com.kaidin.appframe.service.dao.impl.BaseDaoHibernateImpl;
import com.kaidin.db.dao.IEntityRltUserRoleDao;
import com.kaidin.db.entity.EntityRltUserRole;

/**
 * EntityRltUserRoleDaoImpl generated by Hibernate Tools 3.3.0.GA
 * @date 2020-9-1 17:02:04
 */
@Repository(IEntityRltUserRoleDao.RESOURCE_NAME)
public class EntityRltUserRoleDaoImpl extends BaseDaoHibernateImpl<EntityRltUserRole> implements IEntityRltUserRoleDao {

	public EntityRltUserRoleDaoImpl() throws Exception {
		super(EntityRltUserRole.class);
	}
}
