package com.kaidin.db.dao.impl;

import org.springframework.stereotype.Repository;

import com.kaidin.appframe.service.dao.impl.BaseDaoHibernateImpl;
import com.kaidin.db.dao.IEntityCfgRoleDao;
import com.kaidin.db.entity.EntityCfgRole;

/**
 * EntityCfgRoleDaoImpl generated by Hibernate Tools 3.3.0.GA
 * @date 2020-9-1 17:02:04
 */
@Repository(IEntityCfgRoleDao.RESOURCE_NAME)
public class EntityCfgRoleDaoImpl extends BaseDaoHibernateImpl<EntityCfgRole> implements IEntityCfgRoleDao {

	public EntityCfgRoleDaoImpl() throws Exception {
		super(EntityCfgRole.class);
	}
}
