package com.kaidin.db.dao.impl;

import org.springframework.stereotype.Repository;

import com.kaidin.appframe.service.dao.impl.BaseDaoHibernateImpl;
import com.kaidin.db.dao.IEntityCfgUserDao;
import com.kaidin.db.entity.EntityCfgUser;

/**
 * EntityCfgUserDaoImpl generated by Hibernate Tools 3.3.0.GA
 * @date 2020-9-1 17:02:04
 */
@Repository(IEntityCfgUserDao.RESOURCE_NAME)
public class EntityCfgUserDaoImpl extends BaseDaoHibernateImpl<EntityCfgUser> implements IEntityCfgUserDao {

	public EntityCfgUserDaoImpl() throws Exception {
		super(EntityCfgUser.class);
	}
}
