<#if packageName??>package ${packageName};</$if>

import org.springframework.stereotype.Repository;

import com.kaidin.appframe.service.impl.BaseDaoMybatisImpl;
import com.kaidin.db.dao.interfaces.IEntity${entityName ? cap_first}Dao;
import com.kaidin.db.entity.Entity${entityName ? cap_first};

/**
 * Entity${entityName ? cap_first}DaoImpl generated by kaidin
 * @version ${.now ? string("yyyy-MM-dd HH:mm:ss")}
 */
@Repository(IEntity${entityName ? cap_first}Dao.RESOURCE_NAME)
public class Entity${entityName ? cap_first}DaoImpl extends BaseMybatisDaoImpl<Entity${entityName ? cap_first}>
                                   implements IEntity${entityName ? cap_first}Dao {
	/**
	 * 构造函数
	 */
	pubic Entity${entityName ? cap_first}DaoImpl() {
		super(FULL_RESOURCE_NAME)
	}
}
