package com.kaidin.db.entity;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.kaidin.appframe.service.dao.BaseEntity;
/**
 * EntityRltUserRole generated by Hibernate Tools 3.3.0.GA
 * @date 2020-9-1 18:05:22
 */
@Entity
@Table(name="rlt_user_role"
	,catalog="kaidin"
)
public class EntityRltUserRole extends BaseEntity
 {
	private static final long serialVersionUID = 0126L;
	public static final String ENTITY_NAME = "com.kaidin.db.entity.EntityRltUserRole";
	
	public static final String P_EntityCfgUser	= "entityCfgUser";
	public static final String P_EntityCfgRole	= "entityCfgRole";

	private EntityCfgUser entityCfgUser;
	private EntityCfgRole entityCfgRole;

	// default constructor
	public EntityRltUserRole() {
	}
	public EntityRltUserRole(long id, EntityCfgUser entityCfgUser, EntityCfgRole entityCfgRole) {
		this.id = id;
		this.entityCfgUser = entityCfgUser;
		this.entityCfgRole = entityCfgRole;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
	public EntityCfgUser getEntityCfgUser() {
		return this.entityCfgUser;
	}
	public void setEntityCfgUser(EntityCfgUser entityCfgUser) {
		this.entityCfgUser = entityCfgUser;
	}
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
	public EntityCfgRole getEntityCfgRole() {
		return this.entityCfgRole;
	}
	public void setEntityCfgRole(EntityCfgRole entityCfgRole) {
		this.entityCfgRole = entityCfgRole;
	}


	public boolean equals(Object other) {
		if (this == other) return true;
		if (other == null) return false;
		if (!(other instanceof EntityRltUserRole)) return false;
		EntityRltUserRole castOther = (EntityRltUserRole) other;
		return this.getId() == castOther.getId();
	}
	
	public int hashCode() {
		String code = ENTITY_NAME + ":" + this.getId();
		return code.hashCode();
	}
}
