package com.kaidin.db.entity;
// Generated 2017-5-29 14:00:53 by Hibernate Tools 3.3.0.GA
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.kaidin.appframe.entity.BaseEntity;
/**
 * EntityMemberInfo generated by hbm2java
 */
@Entity
@Table(name="member_info"
	,catalog="my"
)
public class EntityMemberInfo extends BaseEntity
 {
	private static final long serialVersionUID = 0126L;
	public static final String ENTITY_NAME = "com.kaidin.db.entity.EntityMemberInfo";
	public static final String P_Id	= "id";
	public static final String P_Name	= "name";
	public static final String P_Password	= "password";
	public static final String P_Alias	= "alias";
	public static final String P_Gender	= "gender";
	public static final String P_Mail	= "mail";
	public static final String P_Birthday	= "birthday";
	public static final String P_Telphone	= "telphone";
	public static final String P_Address	= "address";
	public static final String P_LastLoginTime	= "lastLoginTime";
	public static final String P_PasswordChangeTime	= "passwordChangeTime";
	public static final String P_CreateTime	= "createTime";
	public static final String P_ModifyTime	= "modifyTime";
	public static final String P_Status	= "status";
	public static final String P_Description	= "description";
	public static final String P_WeChat	= "weChat";

	// id
	private long id;
	// 登陆用户名
	private String name;
	// 登陆密码
	private String password;
	// 别名
	private String alias;
	// 性别
	private String gender;
	// 邮箱地址
	private String mail;
	// 生日
	private Date birthday;
	// 电话
	private String telphone;
	// 地址
	private String address;
	// 最后登陆时间
	private Date lastLoginTime;
	// 最后修改时间
	private Date passwordChangeTime;
	// 创建时间
	private Date createTime;
	// 最后修改时间
	private Date modifyTime;
	// 状态
	private String status;
	// 描述信息
	private String description;
	// 微信号
	private String weChat;

	// default constructor
	public EntityMemberInfo() {
	}
	public EntityMemberInfo(String name, Date createTime) {
		this.name = name;
		this.createTime = createTime;
	}
	public EntityMemberInfo(String name, String password, String alias, String gender, String mail, Date birthday, String telphone, String address, Date lastLoginTime, Date passwordChangeTime, Date createTime, Date modifyTime, String status, String description, String weChat) {
		this.name = name;
		this.password = password;
		this.alias = alias;
		this.gender = gender;
		this.mail = mail;
		this.birthday = birthday;
		this.telphone = telphone;
		this.address = address;
		this.lastLoginTime = lastLoginTime;
		this.passwordChangeTime = passwordChangeTime;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.status = status;
		this.description = description;
		this.weChat = weChat;
	}

    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
	public long getId() {
		return this.id;
	}
	public void setId(long id) {
		this.id = id;
	}
    
    @Column(name="name", nullable=false, length=64)
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
    
    @Column(name="password", length=32)
	public String getPassword() {
		return this.password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
    
    @Column(name="alias", length=64)
	public String getAlias() {
		return this.alias;
	}
	public void setAlias(String alias) {
		this.alias = alias;
	}
    
    @Column(name="gender", length=10)
	public String getGender() {
		return this.gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
    
    @Column(name="mail", length=256)
	public String getMail() {
		return this.mail;
	}
	public void setMail(String mail) {
		this.mail = mail;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="birthday", length=10)
	public Date getBirthday() {
		return this.birthday;
	}
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
    
    @Column(name="telphone", length=64)
	public String getTelphone() {
		return this.telphone;
	}
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}
    
    @Column(name="address", length=512)
	public String getAddress() {
		return this.address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login_time", length=19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="password_change_time", length=19)
	public Date getPasswordChangeTime() {
		return this.passwordChangeTime;
	}
	public void setPasswordChangeTime(Date passwordChangeTime) {
		this.passwordChangeTime = passwordChangeTime;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
	public Date getCreateTime() {
		return this.createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_time", length=19)
	public Date getModifyTime() {
		return this.modifyTime;
	}
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
    
    @Column(name="status", length=8)
	public String getStatus() {
		return this.status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
    
    @Column(name="description", length=128)
	public String getDescription() {
		return this.description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
    
    @Column(name="weChat", length=64)
	public String getWeChat() {
		return this.weChat;
	}
	public void setWeChat(String weChat) {
		this.weChat = weChat;
	}


	public boolean equals(Object other) {
		if (this == other) return true;
		if (other == null) return false;
		if (!(other instanceof EntityMemberInfo)) return false;
		EntityMemberInfo castOther = (EntityMemberInfo) other;
		return this.getId() == castOther.getId();
	}
	
	public int hashCode() {
		String code = ENTITY_NAME + ":" + this.getId();
		return code.hashCode();
	}
}
