/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java", 0)}
 */
 <#if is_shard>
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} 
 extends com.certus.isa.entity.${entity_name} 
 <#else>
 ${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${entity_name} 
 extends com.certus.appframe.entity.BaseEntity 
</#if> 