package com.kaidin.db.entity;
// Generated 2015-10-21 10:39:48 by Hibernate Tools 3.3.0.GA
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.kaidin.appframe.entity.BaseEntity;
/**
 * EntityCfgRole generated by hbm2java
 */
@Entity
@Table(name="cfg_role"
	,catalog="kaidin"
)
public class EntityCfgRole extends BaseEntity
 {
	private static final long serialVersionUID = 0126L;
	public static final String ENTITY_NAME = "com.kaidin.db.entity.EntityCfgRole";
	public static final String P_Id	= "id";
	public static final String P_Name	= "name";
	public static final String P_CreateTime	= "createTime";
	public static final String P_Status	= "status";
	public static final String P_Desc	= "desc";
	public static final String P_EntityRltUserRoles	= "entityRltUserRoles";

   	private long id;
	// 角色名
   	private String name;
	// 创建时间
   	private Date createTime;
	// 状态
   	private short status;
	// 描述信息
   	private String desc;
   	private Set<EntityRltUserRole> entityRltUserRoles= new HashSet<EntityRltUserRole>(0);

	// default constructor
	public EntityCfgRole() {
	}
	public EntityCfgRole(long id, short status) {
		this.id = id;
		this.status = status;
	}
	public EntityCfgRole(long id, String name, Date createTime, short status, String desc, Set<EntityRltUserRole> entityRltUserRoles) {
		this.id = id;
		this.name = name;
		this.createTime = createTime;
		this.status = status;
		this.desc = desc;
		this.entityRltUserRoles = entityRltUserRoles;
	}

    @Id 
    
    @Column(name="id", unique=true, nullable=false)
	public long getId() {
		return this.id;
	}
	public void setId(long id) {
		this.id = id;
	}
    
    @Column(name="name", length=32)
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
	public Date getCreateTime() {
		return this.createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
    
    @Column(name="status", nullable=false)
	public short getStatus() {
		return this.status;
	}
	public void setStatus(short status) {
		this.status = status;
	}
    
    @Column(name="desc", length=128)
	public String getDesc() {
		return this.desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
	@OneToMany(fetch=FetchType.LAZY, mappedBy="entityCfgRole")
	public Set<EntityRltUserRole> getEntityRltUserRoles() {
		return this.entityRltUserRoles;
	}
	public void setEntityRltUserRoles(Set<EntityRltUserRole> entityRltUserRoles) {
		this.entityRltUserRoles = entityRltUserRoles;
	}


	public boolean equals(Object other) {
		if (this == other) return true;
		if (other == null) return false;
		if (!(other instanceof EntityCfgRole)) return false;
		EntityCfgRole castOther = (EntityCfgRole) other;
		return this.getId() == castOther.getId();
	}
	
	public int hashCode() {
		String code = ENTITY_NAME + ":" + this.getId();
		return code.hashCode();
	}
	
	/**
	 * getConstraintSet
	 * @return Set<BaseEntity>
	 */
	@Transient
	public Set<BaseEntity> getConstraintSet() {
		Set<BaseEntity> result = new HashSet<BaseEntity>();
		
		result.addAll(this.entityRltUserRoles);
		
		return result;
	}
}
