package com.kaidin.db.entity;
// Generated 2015-12-7 17:00:26 by Hibernate Tools 3.3.0.GA
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.kaidin.appframe.entity.BaseEntity;
/**
 * EntityTAreainfo generated by hbm2java
 */
@Entity
@Table(name="t_areainfo"
	,catalog="kaidin"
)
public class EntityTAreainfo extends BaseEntity
 {
	private static final long serialVersionUID = 0126L;
	public static final String ENTITY_NAME = "com.kaidin.db.entity.EntityTAreainfo";
	public static final String P_Id	= "id";
	public static final String P_Level	= "level";
	public static final String P_Name	= "name";
	public static final String P_ParentId	= "parentId";
	public static final String P_Status	= "status";

	private long id;
	private Integer level;
	private String name;
	private Integer parentId;
	private Integer status;

	// default constructor
	public EntityTAreainfo() {
	}
	public EntityTAreainfo(Integer level, String name, Integer parentId, Integer status) {
		this.level = level;
		this.name = name;
		this.parentId = parentId;
		this.status = status;
	}

    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
	public long getId() {
		return this.id;
	}
	public void setId(long id) {
		this.id = id;
	}
    
    @Column(name="level")
	public Integer getLevel() {
		return this.level;
	}
	public void setLevel(Integer level) {
		this.level = level;
	}
    
    @Column(name="name")
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
    
    @Column(name="parentId")
	public Integer getParentId() {
		return this.parentId;
	}
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
    
    @Column(name="status")
	public Integer getStatus() {
		return this.status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}


	public boolean equals(Object other) {
		if (this == other) return true;
		if (other == null) return false;
		if (!(other instanceof EntityTAreainfo)) return false;
		EntityTAreainfo castOther = (EntityTAreainfo) other;
		return this.getId() == castOther.getId();
	}
	
	public int hashCode() {
		String code = ENTITY_NAME + ":" + this.getId();
		return code.hashCode();
	}
}
