package com.kaidin.db.entity;
// Generated 2017-5-29 14:00:53 by Hibernate Tools 3.3.0.GA
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.kaidin.appframe.entity.BaseEntity;
/**
 * EntityUser generated by hbm2java
 */
@Entity
@Table(name="user"
	,catalog="my"
)
public class EntityUser extends BaseEntity
 {
	private static final long serialVersionUID = 0126L;
	public static final String ENTITY_NAME = "com.kaidin.db.entity.EntityUser";
	public static final String P_Id	= "id";
	public static final String P_Password	= "password";
	public static final String P_Username	= "username";

	private long id;
	private String password;
	private String username;

	// default constructor
	public EntityUser() {
	}
	public EntityUser(String password, String username) {
		this.password = password;
		this.username = username;
	}

    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
	public long getId() {
		return this.id;
	}
	public void setId(long id) {
		this.id = id;
	}
    
    @Column(name="password", length=100)
	public String getPassword() {
		return this.password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
    
    @Column(name="username", length=100)
	public String getUsername() {
		return this.username;
	}
	public void setUsername(String username) {
		this.username = username;
	}


	public boolean equals(Object other) {
		if (this == other) return true;
		if (other == null) return false;
		if (!(other instanceof EntityUser)) return false;
		EntityUser castOther = (EntityUser) other;
		return this.getId() == castOther.getId();
	}
	
	public int hashCode() {
		String code = ENTITY_NAME + ":" + this.getId();
		return code.hashCode();
	}
}
