package com.kaidin.db.entity;
// Generated 2015-10-21 10:39:48 by Hibernate Tools 3.3.0.GA
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.kaidin.appframe.entity.BaseEntity;
/**
 * EntityStudent generated by hbm2java
 */
@Entity
@Table(name="student"
	,catalog="kaidin"
)
public class EntityStudent extends BaseEntity
 {
	private static final long serialVersionUID = 0126L;
	public static final String ENTITY_NAME = "com.kaidin.db.entity.EntityStudent";
	public static final String P_Id	= "id";
	public static final String P_Name	= "name";
	public static final String P_Psw	= "psw";

   	private long id;
   	private String name;
   	private String psw;

	// default constructor
	public EntityStudent() {
	}
	public EntityStudent(String name, String psw) {
		this.name = name;
		this.psw = psw;
	}

    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
	public long getId() {
		return this.id;
	}
	public void setId(long id) {
		this.id = id;
	}
    
    @Column(name="name", nullable=false, length=45)
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
    
    @Column(name="psw", nullable=false, length=45)
	public String getPsw() {
		return this.psw;
	}
	public void setPsw(String psw) {
		this.psw = psw;
	}


	public boolean equals(Object other) {
		if (this == other) return true;
		if (other == null) return false;
		if (!(other instanceof EntityStudent)) return false;
		EntityStudent castOther = (EntityStudent) other;
		return this.getId() == castOther.getId();
	}
	
	public int hashCode() {
		String code = ENTITY_NAME + ":" + this.getId();
		return code.hashCode();
	}
}
