package com.kaidin.db.entity;
// Generated 2015-10-21 10:39:48 by Hibernate Tools 3.3.0.GA
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.kaidin.appframe.entity.BaseEntity;
/**
 * EntityRltUserRole generated by hbm2java
 */
@Entity
@Table(name="rlt_user_role"
	,catalog="kaidin"
)
public class EntityRltUserRole extends BaseEntity
 {
	private static final long serialVersionUID = 0126L;
	public static final String ENTITY_NAME = "com.kaidin.db.entity.EntityRltUserRole";
	public static final String P_Id	= "id";
	public static final String P_EntityCfgUser	= "entityCfgUser";
	public static final String P_EntityCfgRole	= "entityCfgRole";

   	private long id;
   	private EntityCfgUser entityCfgUser;
   	private EntityCfgRole entityCfgRole;

	// default constructor
	public EntityRltUserRole() {
	}
	public EntityRltUserRole(long id, EntityCfgUser entityCfgUser, EntityCfgRole entityCfgRole) {
		this.id = id;
		this.entityCfgUser = entityCfgUser;
		this.entityCfgRole = entityCfgRole;
	}

    @Id 
    
    @Column(name="id", unique=true, nullable=false)
	public long getId() {
		return this.id;
	}
	public void setId(long id) {
		this.id = id;
	}
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
	public EntityCfgUser getEntityCfgUser() {
		return this.entityCfgUser;
	}
	public void setEntityCfgUser(EntityCfgUser entityCfgUser) {
		this.entityCfgUser = entityCfgUser;
	}
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
	public EntityCfgRole getEntityCfgRole() {
		return this.entityCfgRole;
	}
	public void setEntityCfgRole(EntityCfgRole entityCfgRole) {
		this.entityCfgRole = entityCfgRole;
	}


	public boolean equals(Object other) {
		if (this == other) return true;
		if (other == null) return false;
		if (!(other instanceof EntityRltUserRole)) return false;
		EntityRltUserRole castOther = (EntityRltUserRole) other;
		return this.getId() == castOther.getId();
	}
	
	public int hashCode() {
		String code = ENTITY_NAME + ":" + this.getId();
		return code.hashCode();
	}
}
